### ISSUE TITLE
Remember the last comic

### ISSUE THREAD

**Issue by trajano** [aicd0/ComicReaderUWP#1]
**Problem Statement**
In case I close the app I want it to remember where I was on the comic so I can continue later.

**Evidence or User Insights**

**Proposal**

**Goals**

**Non-Goals**

* Only do it for local files that can be read in quickly.  Remote files just let it do it normally because it will take time for it to load.

**Low-Fidelity Concept**

**Requested Assignment**

If possible, I would like to implement this.
I'm just suggesting this idea. I don't want to implement it.

**Comment by aicd0** [comment]
Thanks for your suggestion. I will consider adding it in a future version.

**Comment by aicd0** [comment]
This feature is now supported in 1.4.0
