### ISSUE TITLE
当漫画文件夹位于 OneDrive 文件夹中时，无法识别和阅读该漫画

### ISSUE THREAD

**Issue by JianXiao2021** [aicd0/ComicReaderUWP#4]
**bug 描述**：
操作系统为 Windows11 家庭中文版。我有一个名为 ”OneDrive" 的文件夹用于 Microsoft OneDrive 的同步。我发现，当要添加的漫画文件夹位于此文件夹中时，添加该漫画文件夹后，漫画不会显示在上方的“库”中，无法阅读该漫画。如果将漫画文件夹移动到其它非 OneDrive 文件夹中，则添加该文件夹后漫画可以正常显示在“库”中，并且可以正常阅读

**复现步骤**：
1. 有一个用于 OneDrive 同步的文件夹（其图标显示为一朵蓝色云），漫画文件夹位于此文件夹中
2. 打开 ComicReader，点击“文件夹”下的“添加文件夹”，找到该漫画文件夹并打开
3. 新添加的漫画文件夹已显示在“文件夹”中，但上方的“库”中并未见到该漫画，因此无法阅读该漫画

**设备信息**：
 - OS Build: 10.0.22621.0
 - Architecture: X64
 - Application Version: 1.3.3.0
 - Region: zh-CN
 - Dev Version Installed: 49915aicd.ComicReaderUWP.Dev

**附加信息**：
当把出问题的漫画文件夹移动到其它非 OneDrive 文件夹中时，则添加该文件夹后漫画可以正常显示在“库”中，并且可以正常阅读

**Requested Assignment**
I'm just reporting this problem.  I don't want to fix it.

**Comment by aicd0** [comment]
应用程序想要访问OneDrive中的文件需要经过OneDrive的权限认证流程，如果有需要的话可以先使用RaiDrive类似的软件将OneDrive映射成本地磁盘后再添加文件夹。
