### ISSUE TITLE
文件夹排序错误，第09话后面是第100话；切换标签页自动回顶也令体验不太好。

### ISSUE THREAD

**Issue by SalicylicAcid** [aicd0/ComicReaderUWP#5]
![image](https://github.com/aicd0/ComicReader/assets/37034452/22a8f9fb-cca6-4a0b-bf99-8569ed08e185)

**Comment by aicd0** [comment]
排序问题已经修复，自动回顶需要提供更多信息以便于复现问题

**Comment by SalicylicAcid** [comment]
> 排序问题已经修复，自动回顶需要提供更多信息以便于复现问题

![Uploading 1.gif…]()

**Comment by SalicylicAcid** [comment]
> 排序问题已经修复，自动回顶需要提供更多信息以便于复现问题

![1](https://github.com/aicd0/ComicReader/assets/37034452/2132b6be-5e90-413a-a131-fb73db3c4f0d)
如图所示

**Comment by aicd0** [comment]
1.5.1已修复
